[tool.pytest.ini_options]
addopts = ["-rfEX", "--cov-report=", "--cov-append"]
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests"]

[tool.flake8]
max_line_length = 120
max_complexity = 14
inline_quotes = "double"
multiline_quotes = "double"
ignore = ["E203", "W503"]
exclude = "tools/gen_python_packages,bazel-*/,venv,**/tests,typings"


[tool.ruff]
line-length = 120
extend-select = ['Q']
flake8-quotes = { inline-quotes = 'double', multiline-quotes = 'double' }
exclude = [
  "tools/gen_python_packages",
  "bazel-*/",
  "venv",
  "**/tests",
  "typings",
]

[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | \.build
    | venv
    | _build
    | build
    | bazel-*
    | lib
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
force_single_line = true
order_by_type = true
known_first_party = "bentoml"
force_alphabetical_sort_within_sections = true
skip_glob = ["test/*", "venv/*", "lib/*", "bazel-*"]

[tool.pyright]
pythonVersion = "3.11"
exclude = [
  "tools/gen_python_packages",
  "bazel-*/",
  "venv",
  "**/tests",
  "typings",
]
venv = ["venv"]
typeCheckingMode = "strict"
analysis.useLibraryCodeForTypes = true
enableTypeIgnoreComments = true
reportMissingTypeStubs = "warning"
