name: Setup repo
description: Setup repo with all features on CI
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.10"
  architecture:
    description: "Which architecture to run on"
    required: true
    default: x64
runs:
  using: composite
  steps:
    - name: Fetch base reference.
      shell: bash
      run: git fetch origin $GITHUB_BASE_REF
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Get cache key prefix
      id: get-cache-key-prefix
      shell: bash
      run: echo "prefix=${{ runner.os }}-${{ inputs.python-version }}" >> $GITHUB_OUTPUT
    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: echo "directory=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: Bazel cache
      id: bazel-cache
      uses: actions/cache@v3
      with:
        key: ${{ steps.get-cache-key-prefix.outputs.prefix }}-bazel
        path: |
          ~/.cache/bazel
          tools/
        restore-keys: |
          ${{ steps.get-cache-key-prefix.outputs.prefix }}-bazel-
    - name: Cache PyPI
      id: cache-pypi
      uses: actions/cache@v3.0.10
      with:
        key: ${{ steps.get-cache-key-prefix.outputs.prefix }}-pypi
        path: ${{ steps.pip-cache.outputs.directory }}
        restore-keys: |
          ${{ steps.get-cache-key-prefix.outputs.prefix }}-pypi-
    - name: Run updating dependencies
      shell: bash
      run: bazel run //:pypi.update
    - name: Install development dependencies
      shell: bash
      run: |
        python -m pip install ruff
        python -m pip install git+https://github.com/bentoml/bentoml.git@main
