name: CI

concurrency:
  group: ci-${{ github.event.pull_request.number || github.sha }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 0 * * 1/2" # Every other day 12AM UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "requirements/**"
      - ".github/actions/**"
      - "BUILD.bazel"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"
      - "monitoring/**"

env:
  LINES: 200
  COLUMNS: 200
  BENTOML_DEBUG: True
  BENTOML_DO_NOT_TRACK: True
  PYTEST_PLUGINS: bentoml.testing.pytest.plugin

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  monitoring-tests:
    runs-on: ubuntu-latest
    if: "!github.event.repository.fork" # Don't run on fork repository
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
        packages: ["bentoml-plugins-arize"]
    name: python${{ matrix.python-version }} tests for ${{ matrix.packages }} (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup CI
        uses: ./.github/actions/setup-repo
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run python${{ matrix.python-version }} tests
        run: bazel test //monitoring/bentoml-plugins-arize/tests/...
