name: Style

concurrency:
  group: style-check-${{ github.event.pull_request.number || github.sha }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 0 * * 1/2" # Every other day 12AM UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "requirements/**"
      - ".github/actions/**"
      - "pyproject.toml"
      - ".github/workflows/style.yml"

env:
  LINES: 200
  COLUMNS: 200
  BENTOML_DEBUG: True
  BENTOML_DO_NOT_TRACK: True
  PYTEST_PLUGINS: bentoml.testing.pytest.plugin

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  format:
    runs-on: ubuntu-latest
    if: "!github.event.repository.fork" # Don't run on fork repository
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Run format
        run: ./scripts/format

  lint:
    needs: format
    runs-on: ubuntu-latest
    if: "!github.event.repository.fork" # Don't run on fork repository
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Run lint
        run: ./scripts/lint
      - name: (pylint) Running lint on folders
        run: pylint monitoring bentoml-monitoring
